# Generated by Django 2.2.5 on 2019-09-23 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200)),
                ('ingredientes', models.CharField(max_length=300)),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=100)),
                ('modo_preparo', models.TextField()),
                ('foto_1', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('foto_2', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('foto_3', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('publicada', models.BooleanField(default=True)),
                ('data_receita', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pessoas.Pessoa')),
            ],
        ),
    ]
